repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: ^src/config/static/vendor/.*$
      - id: check-yaml
        exclude: ^docker/mkdocs/mkdocs\.yml$
      - id: check-added-large-files

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.1
    hooks:
      - id: ruff
        files: ^src/.*\.py$
      - id: ruff-format
        args: [--check]
        files: ^src/.*\.py$
